"""
Pydantic schemas — request and response shapes for every endpoint.

every API response follows one of these models. FastAPI uses them to:
    1. validate payloads at the boundary, before any business code runs
    2. generate the OpenAPI / Swagger docs at /docs automatically
    3. produce stable JSON output with the right types every time

design choice — schemas separate from the inference layer:
    inference.py returns a PredictionResult dataclass. schemas.py
    converts it to a JSON-friendly Pydantic model. the boundary keeps
    the two concerns clean — inference can change shape without
    breaking the API contract, and the API contract can add fields
    without touching inference.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class HealthResponse(BaseModel):
    """response shape for GET /health.

    used by the load balancer + Docker healthcheck. minimal payload
    so the check finishes in microseconds.
    """
    status: str = Field(..., examples=["ok"])
    age_model_loaded: bool
    pad_model_loaded: bool


class EstimateAgeResponse(BaseModel):
    """response shape for POST /estimate-age.

    note — model_config below silences a pydantic warning. fields starting
    with `model_` overlap pydantic's protected namespace (it reserves names
    like `model_dump`, `model_copy`). `model_version` here is intentional
    and does not collide; the empty protected_namespaces tuple disables the
    over-eager check.

    fields:
        is_spoof        — true if PAD flagged this image as an attack
        pad_score       — P(attack) from the PAD model, 0.0 to 1.0
        estimated_age   — predicted age in years; None when is_spoof=true
        age_confidence  — model self-confidence on the prediction, 0.0 to 1.0
        inference_ms    — wall-clock time the API spent running the models
        model_version   — string version tag, lets the client log which
                          model produced the result. set on app startup.
    """
    model_config = ConfigDict(protected_namespaces=())

    is_spoof: bool
    pad_score: float = Field(..., ge=0.0, le=1.0)
    estimated_age: Optional[float] = Field(None, ge=0.0, le=100.0)
    age_confidence: Optional[float] = Field(None, ge=0.0, le=1.0)
    inference_ms: float = Field(..., ge=0.0)
    model_version: str


class ExplainResponse(BaseModel):
    """response shape for POST /explain.

    saliency_map is a 2D list of floats, normalised to [0, 1]. row-major
    layout, 224x224 to match the model input. consumers (Streamlit,
    notebook, third-party clients) can render it as a heatmap.

    rationale for nested list of floats vs base64-encoded PNG:
        keeps the API output JSON-only, no client-side image decoder
        required. payload is roughly 200 KB at full resolution which is
        small enough for a real-time UI.
    """
    saliency_map: list[list[float]]
    baseline_age: float = Field(..., ge=0.0, le=100.0)
    inference_ms: float = Field(..., ge=0.0)
    grid: int = Field(..., ge=2, le=64)
    image_size: int = Field(..., ge=32, le=1024)


class BiasGroup(BaseModel):
    """one row from the bias report — matches the structure written by Phase 5."""
    group_type: str
    group_name: str
    n_samples: int
    mae: float
    rmse: float


class BiasOverall(BaseModel):
    """top-line metrics from the bias report."""
    n_samples: int
    mae: float
    rmse: float


class BiasWorstGap(BaseModel):
    """headline fairness number — worst single-group MAE vs overall."""
    worst_group: Optional[str] = None
    worst_mae: Optional[float] = None
    gap_years: Optional[float] = None


class BiasReportResponse(BaseModel):
    """response shape for GET /bias-report.

    reads the JSON file written by src/audit/bias_audit.py (Phase 5)
    and returns it through a typed response. file is regenerated by
    running the audit notebook; the API just serves what is on disk.
    """
    overall: BiasOverall
    groups: list[BiasGroup]
    worst_gap: BiasWorstGap


class ErrorResponse(BaseModel):
    """uniform error shape for every 4xx / 5xx path."""
    detail: str
